insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Ms');

insert into COURSE_MATERIAL (url, course_id) values ('http://mashable.com/pede.xml', 1);
insert into COURSE_MATERIAL (url, course_id) values ('https://jugem.jp/ipsum/ac/tellus/semper/interdum/mauris.json', 2);
insert into COURSE_MATERIAL (url, course_id) values ('https://cocolog-nifty.com/massa/id/nisl/venenatis.png', 3);
insert into COURSE_MATERIAL (url, course_id) values ('http://berkeley.edu/eget/rutrum/at/lorem/integer.js', 4);
insert into COURSE_MATERIAL (url, course_id) values ('https://bigcartel.com/turpis/enim/blandit/mi/in/porttitor.png', 5);
insert into COURSE_MATERIAL (url, course_id) values ('https://google.co.jp/pede/ullamcorper/augue/a/suscipit/nulla/elit.xml', 6);
insert into COURSE_MATERIAL (url, course_id) values ('http://addtoany.com/amet/turpis/elementum/ligula/vehicula/consequat/morbi.png', 7);
insert into COURSE_MATERIAL (url, course_id) values ('http://ifeng.com/pede/malesuada/in/imperdiet/et.jpg', 8);
insert into COURSE_MATERIAL (url, course_id) values ('http://opera.com/curabitur/in.json', 9);
insert into COURSE_MATERIAL (url, course_id) values ('https://latimes.com/velit/id/pretium/iaculis/diam/erat/fermentum.html', 10);